# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_bridge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'audio_bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61udio_bridge.proto\x12\x0b\x61udiobridge\"+\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"C\n\x13TranscriptionResult\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05\x61udio\x18\x03 \x01(\x0c\x32\\\n\x0c\x41udioService\x12L\n\x0bStreamAudio\x12\x17.audiobridge.AudioChunk\x1a .audiobridge.TranscriptionResult(\x01\x30\x01\x42\x0eZ\x0cjarvis-go/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014jarvis-go/pb'
  _globals['_AUDIOCHUNK']._serialized_start=35
  _globals['_AUDIOCHUNK']._serialized_end=78
  _globals['_TRANSCRIPTIONRESULT']._serialized_start=80
  _globals['_TRANSCRIPTIONRESULT']._serialized_end=147
  _globals['_AUDIOSERVICE']._serialized_start=149
  _globals['_AUDIOSERVICE']._serialized_end=241
# @@protoc_insertion_point(module_scope)
